workspace:
  base: /drone
  path: src

branches:
  - 10

pipeline:
  dryrun:
    image: plugins/docker:17.05
    pull: true
    secrets: [ docker_username, docker_password ]
    repo: owncloudci/nodejs
    label_schema:
      - version=${DRONE_BRANCH}
    dry_run: true
    tags:
      - 10
      - 10.x
    when:
      event: [ pull_request ]

  docker:
    image: plugins/docker:17.05
    pull: true
    secrets: [ docker_username, docker_password ]
    repo: owncloudci/nodejs
    label_schema:
      - version=${DRONE_BRANCH}
    tags:
      - 10
      - 10.x
    when:
      event: [ push ]

  microbadger:
    image: plugins/webhook:1
    pull: true
    secrets:
      - source: microbadger_token
        target: plugin_urls
    when:
      event: [ push ]

  slack:
    image: plugins/slack:1
    pull: true
    secrets: [ slack_webhook ]
    channel: drone
    when:
      event: [ push, pull_request ]
      status: [ success, failure ]
